# Generated by Django 5.1.1 on 2024-12-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Placement',
            new_name='Placements',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
