# Generated by Django 5.1.1 on 2024-12-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='f_name',
            field=models.CharField(default='zz', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='l_name',
            field=models.CharField(default='aa', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Hey there I am using campus connect!'),
        ),
    ]
