# Generated by Django 5.1.1 on 2024-12-01 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_profile_f_name_profile_l_name_alter_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='l_name',
        ),
    ]
