# Generated by Django 5.1.1 on 2024-12-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_remove_profile_f_name_remove_profile_l_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date_posted',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
