# Generated by Django 5.1.1 on 2024-12-02 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0006_rename_date_posted_announcement_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='start_date',
            new_name='date_posted',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='end_date',
        ),
    ]
